<a href="https://colab.research.google.com/github/aiswaryajoseph2004-bot/Deep-learning-/blob/main/deep_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tesorflow

## Tensor

### **Scalar (OD Tensor)**

In [ ]:
import tensorflow as tf
scalar=tf.constant(5)    #single number
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


### **vector(1D Tensor)**

In [ ]:
import tensorflow as tf
vector =tf.constant([5,10,15,20])
print(vector)

tf.Tensor([ 5 10 15 20], shape=(4,), dtype=int32)


### **Matrix (2D tensor)**

In [ ]:
from numpy import matrix
import tensorflow as tf
matrix=tf.constant ([[1,2,3],[4,5,6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


### **3D tensor **

In [ ]:
tensor_3d=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor_3d)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


### **Higher - dimensional tensor(4d,5d,etc)**

In [ ]:
tensor_4d=tf.constant([[[[1],[2]],[[3],[4]],[[5],[6]],[[7],[8]]]])
print(tensor_4d)

tf.Tensor(
[[[[1]
   [2]]

  [[3]
   [4]]

  [[5]
   [6]]

  [[7]
   [8]]]], shape=(1, 4, 2, 1), dtype=int32)


### tf constant()

In [ ]:
import tensorflow as tf
tensor =tf.constant([[1,2],[3,4]])
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


### tf.zeros()

In [ ]:
import tensorflow as tf
zero_tensor=tf.zeros([2,3])
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### tf.ones()

In [ ]:
import tensorflow as tf
one_tensor=tf.ones([2,3])
print(one_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


### tf.random.uniform()

In [ ]:
import tensorflow as tf
random_tensor=tf.random.uniform([2,2],minval=0,maxval=10,dtype=tf.int32)
print(random_tensor)

tf.Tensor(
[[5 6]
 [9 5]], shape=(2, 2), dtype=int32)


### tf.shape()

In [ ]:
import tensorflow as tf
tensor=tf.constant([[1,2],[3,4]])
print(tf.shape(tensor))

tf.Tensor([2 2], shape=(2,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.add(a,b)
print(c)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.subtract(a,b)
print(c)

tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.multiply(a,b)
print(c)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
c=tf.divide(a,b)
print(c)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [ ]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(matrix1, matrix2)
print(result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# Reshaping & Manipulating Tensors

### 1.   tf.reshape() - Changes tensor shap
2.   tf.transpose() - Transposes a matrix
3.  tf.squeeze() - Removes dimensions of size 1
4.  tf.expand_dims() - Adds a new dimension

In [ ]:
import tensorflow as tf
tensor = tf.constant([1, 2, 3, 4, 5, 6])
reshaped_tensor = tf.reshape(tensor, [2, 3])
print(reshaped_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
transposed = tf.transpose(matrix)
print(transposed)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [ ]:
import tensorflow as tf
tensor = tf.constant([[[1], [2], [3]]])
squeezed = tf.squeeze(tensor)
print(squeezed)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
tensor = tf.constant([1, 2, 3])
expanded = tf.expand_dims(tensor, axis=1)
print(expanded)

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)


# Aggregation Functions (Summarizing Data)

### 1. tf.reduce_sum() - Computes sum of all elements
2. tf.reduce_mean() - Computes mean (average)
3. tf.reduce_max() & tf.reduce_min() - Finds max/min


In [ ]:
import tensorflow as tf
tensor=tf.constant(([1,2],[3,4]))
sum=tf.reduce_sum(tensor)
print(sum)

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
mean_result=tf.reduce_mean(tensor)
print(mean_result)

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
mean_result=tf.reduce_min(tensor)
print(mean_result)

tf.Tensor(1, shape=(), dtype=int32)


## indexing & slicing tensors

In [ ]:
import tensorflow as tf
tensor = tf.constant([1, 2, 3, 4, 5])
print(tensor[0])
print(tensor[-1])

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
tensor = tf.constant([10, 20, 30, 40, 50])
print(tensor[1:4])

tf.Tensor([20 30 40], shape=(3,), dtype=int32)


## Boardcasting in Tensor

In [ ]:
import tensorflow as tf
tensor1 = tf.constant([[1, 2, 3]])
tensor2 = tf.constant([[1], [2], [3]])

result = tensor1 + tensor2
print(result)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [4 5 6]], shape=(3, 3), dtype=int32)


## Sequential API

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Activation
model=Sequential()
model.add(Dense(units=64,input_dim=100))
model.add(Activation('relu'))
model.add(Dense(units=10))
model.add(Activation('softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


## Functional API


In [ ]:
from keras.layers import Input,Dense,concatenate
from keras.models import Model
input1=Input(shape=(100,))
input2=Input(shape=(50,))
hidden1=Dense(64,activation='relu')(input1)
hidden2=Dense(32,activation='relu')(input2)
merged=concatenate([hidden1,hidden2])
output=Dense(10,activation='softmax')(merged)
model=Model(inputs=[input1,input2],outputs=output)

# feedforward

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [ ]:
x_train=np.array(([1],[2],[3],[4],[5]),dtype=float)
y_train=np.array([[3],[5],[7],[9],[11]],dtype=float)


In [ ]:
model=Sequential([
    Dense(10,activation='relu',input_shape=(1,)),
    Dense(1)
])

In [ ]:
model.compile(optimizer=Adam(learning_rate=0.01),loss='mean_squared_error')

In [ ]:
model.fit(x_train,y_train,epochs=100,verbose=1)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 52.7382
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 379ms/step - loss: 50.2773
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 47.8892
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 45.5740
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 43.3313
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 41.1723
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 39.1016
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 37.2336
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 35.5487
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 33.9053
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 32.3026
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 30.7397
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 29.2155
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 27.7294
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 26.2807
Epoc

In [ ]:
x_test=np.array([[6],[7]],dtype=float)
y_pred=model.predict(x_test)

print("predictions for 6 and 7:",y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 260ms/step
predictions for 6 and 7: [[12.574904]
 [14.421161]]


In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
x_test=np.array([[6],[7]],dtype=float)
y_test=np.array([[13],[15]],dtype=float)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
print(f"predictions:{y_pred.flatten()}")
print(f"Mean Squared Error:{mse}")
print(f"Mean Absolute Error:{mae}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
predictions:[12.574904 14.421161]
Mean Squared Error:0.25788058559282945
Mean Absolute Error:0.5019674301147461


In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

x=np.array([[0],[1],[2],[3],[4],[5]],dtype=float)
y=np.array([[0],[0.5],[1],[1.5],[2],[2.5]],dtype=float)

In [ ]:
model=Sequential([Dense(1,activation='linear',input_shape=(1,))])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(optimizer=SGD(learning_rate=0.1),
              loss='mean_squared_error',
              metrics=['mean_absolute_error'])

In [ ]:
model.fit(x,y,epochs=200,verbose=1)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 576ms/step - loss: 0.2324 - mean_absolute_error: 0.3981
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - loss: 0.2206 - mean_absolute_error: 0.4113
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - loss: 0.2093 - mean_absolute_error: 0.3786
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - loss: 0.1986 - mean_absolute_error: 0.3897
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.1885 - mean_absolute_error: 0.3600
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.1789 - mean_absolute_error: 0.3692
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.1698 - mean_absolute_error: 0.3423
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - loss: 0.1611 - mean_absolute_error: 0.3499
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - loss: 0.1529 - mean_absolute_error: 0.3255
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.1451 - mean_absolute_error: 0.3315
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11

In [ ]:
pred=model.predict(np.array([[1.5]]))
print('prediction for input 1.5:',pred[0][0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
prediction for input 1.5: 0.75142145


## classification

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

x,y=make_classification(n_samples=1000,n_features=20,n_classes=2,random_state=42)

scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,test_size=0.3,random_state=42)

In [ ]:
model = Sequential()
model.add(Dense(64, input_dim=20, activation='relu'))  # Hidden Layer 1
model.add(Dense(32, activation='relu'))               # Hidden Layer 2
model.add(Dense(1, activation='sigmoid'))             # Output Layer

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6064 - loss: 0.6686
Epoch 2/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8232 - loss: 0.5207
Epoch 3/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8649 - loss: 0.4200
Epoch 4/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8757 - loss: 0.3490
Epoch 5/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8808 - loss: 0.3247
Epoch 6/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8981 - loss: 0.2949
Epoch 7/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9227 - loss: 0.2450
Epoch 8/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8969 - loss: 0.2765
Epoch 9/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9185 - loss: 0.2304
Epoch 10/10
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9076 - loss: 0.2702


In [ ]:
probs=model.predict(np.expand_dims(x_test[0],axis=0))
pred_classes=np.round(probs).astype(int)

print('probabilities:\n',probs.flatten())
print()
print('predicted classes(by rounding):',pred_classes.flatten())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step
probabilities:
 [0.6941096]

predicted classes(by rounding): [1]


In [ ]:
loss,accuracy=model.evaluate(x_test,y_test)
print(f"Model Accuracy:{accuracy * 100:.2f}%")

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8694 - loss: 0.3769  
Model Accuracy:85.67%
